apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modulo-contabilidade
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rafael-aguiar01/synthetic-mesh-gitops.git'
    targetRevision: HEAD
    path: contabilidade
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: contabilidade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true