apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: contabilidade-empenhos
  description: Microsserviço de empenhos e liquidações orçamentárias
  tags:
    - nodejs
    - kubernetes
spec:
  type: service
  lifecycle: production
  owner: squad-contabilidade
  system: erp-municipal