apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: contabilidade

resources:
  - ../base

namePrefix: contabilidade-empenhos-

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: SERVICE_NAME
            value: "contabilidade-empenhos"
          - name: PORT
            value: "3000"
          - name: ERROR_RATE
            value: "0.0"
          - name: OTEL_SERVICE_NAME
            value: "tributos-iptu" # No outro arquivo, use "contabilidade-empenhos"