apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: platform

data:
  app-config.yaml: |
    app:
      title: Portal do Desenvolvedor - Sistemas Integrados
      baseUrl: http://backstage.localhost

    backend:
      baseUrl: http://backstage.localhost

      listen:
        port: 7007
        host: 0.0.0.0

      cors:
        origin: http://backstage.localhost
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true

      database:
        client: pg
        connection:
          host: postgres
          port: 5432
          user: backstage
          password: backstage123
          database: backstage

    auth:
      environment: development

      experimentalExtraAllowedOrigins:
        - http://backstage.localhost

      providers:
        github:
          development:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

            signIn:
              resolvers:
                - resolver: usernameMatchingUserEntityName

    catalog:
      locations:
        - type: url
          target: https://raw.githubusercontent.com/rafael-aguiar01/synthetic-mesh-gitops/main/users.yaml
        
        - type: url
          target: https://raw.githubusercontent.com/rafael-aguiar01/synthetic-mesh-gitops/main/contabilidade/catalog-info.yaml

        - type: url
          target: https://raw.githubusercontent.com/rafael-aguiar01/synthetic-mesh-gitops/main/financas/catalog-info.yaml

        - type: url
          target: https://raw.githubusercontent.com/rafael-aguiar01/synthetic-mesh-gitops/main/system.yaml