apiVersion: v1
kind: Secret
metadata:
  name: backstage-secret
  namespace: platform
type: Opaque
data:
  # Insira aqui os seus valores codificados em Base64
  # Exemplo: echo -n "seu_client_id" | base64
  github-client-id: T3YyM2xpODlFWm5KZTJyemwwM2U=
  github-client-secret: ZGIyYzJmYzMyYzgzYmE0M2Y4ODE5N2U5NTk1YmU1ZmU4ZjFlMzg5OQ==