apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: platform

data:
  app-config.yaml: |
    app:
      title: Portal do Desenvolvedor - Sistemas Integrados
      baseUrl: http://backstage.localhost

    backend:
      baseUrl: http://backstage.localhost

      listen:
        port: 7007
        host: 0.0.0.0

      cors:
        origin: http://backstage.localhost
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true

      database:
        client: pg
        connection:
          host: postgres
          port: 5432
          user: backstage
          password: backstage123
          database: backstage

    auth:
      environment: development

      experimentalExtraAllowedOrigins:
        - http://backstage.localhost

      providers:
        github:
          development:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

            signIn:
              resolvers:
                - resolver: usernameMatchingUserEntityName
                  dangerouslyAllowSignInWithoutUserInCatalog: true

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}

    catalog:
      rules:
        - allow:
            - Component
            - System
            - API
            - Resource
            - Location
            - Domain
            - Template


      locations:

        # USUÁRIOS
        - type: url
          target: https://github.com/rafael-aguiar01/synthetic-mesh-gitops/blob/main/users.yaml
          rules:
            - allow: [User, Group]

        # CONTABILIDADE
        - type: url
          target: https://github.com/rafael-aguiar01/synthetic-mesh-gitops/blob/main/contabilidade/catalog-info.yaml

        # FINANÇAS
        - type: url
          target: https://github.com/rafael-aguiar01/synthetic-mesh-gitops/blob/main/financas/catalog-info.yaml

        # SYSTEM
        - type: url
          target: https://github.com/rafael-aguiar01/synthetic-mesh-gitops/blob/main/system.yaml
        
        - type: url
          target: https://github.com/rafael-aguiar01/synthetic-mesh-gitops/blob/main/templates/erp-module/template.yaml
          rules:
            - allow: [Template]

  app-config.production.yaml: |
    {}