apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: financas

resources:
  - ../base
  - ingress.yaml

namePrefix: tributos-iptu-

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: SERVICE_NAME
            value: "tributos-iptu"
          - name: PORT
            value: "3000"
          - name: ERROR_RATE
            value: "0.0"