apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: financas

resources:
  - ../base
  - ingress.yaml

namePrefix: tributos-iptu-

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dummy-service
      spec:
        template:
          spec:
            containers:
            - name: app
              env:
              - name: SERVICE_NAME
                value: "tributos-iptu"
              - name: PORT
                value: "3000"
              - name: ERROR_RATE
                value: "0.0"
              - name: TARGET_UPSTREAMS
                value: "http://contabilidade-empenhos-dummy-service.contabilidade.svc"
              - name: OTEL_SERVICE_NAME
                value: "tributos-iptu"