apiVersion: v1
kind: ConfigMap
metadata:
  name: gsp-code
  namespace: platform
data:
  index.js: |
    const http = require('http');
    const port = 7007;
    const server = http.createServer((req, res) => {
      console.log("Requisicao recebida no modulo: gsp");
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: "UP", module: "gsp" }));
    });
    server.listen(port, () => {
      console.log("Servico gsp rodando na porta " + port);
    });