apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
      - name: app
        # Aponta para o nosso registry local do k3d
        image: mesh-registry:5000/mesh-node:latest
        ports:
        - containerPort: 3000
        env:
        # Ativa o OpenTelemetry sem alterar o server.js
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
        # Define o protocolo e o destino (nosso Jaeger)
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://jaeger.observabilidade.svc:4318/v1/traces"