apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-service
  template:
    metadata:
      labels:
        app: dummy-service
    spec:
      containers:
      - name: app
        # Aponta para o nosso registry local do k3d
        image: mesh-registry:5000/mesh-node:latest
        ports:
        - containerPort: 3000