apiVersion: apps/v1
kind: Deployment
metadata:
  name: social
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
    spec:
      containers:
        - name: app
          image: node:18-alpine
          command: ["node", "/app/index.js"]
          ports:
            - containerPort: 7007
          volumeMounts:
            - name: code-volume
              mountPath: /app
      volumes:
        - name: code-volume
          configMap:
            name: social-code