apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.name }}-code
  namespace: platform
data:
  index.js: |
    const http = require('http');
    const port = 7007;
    const server = http.createServer((req, res) => {
      console.log("Requisicao recebida no modulo: ${{ values.name }}");
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: "UP", module: "${{ values.name }}" }));
    });
    server.listen(port, () => {
      console.log("Servico ${{ values.name }} rodando na porta " + port);
    });