apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: platform
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7007